import logging
from typing import Dict, Any, List, Optional
import json
import ollama
from neuroform.memory.graph import KnowledgeGraph
from neuroform.memory.amygdala import Amygdala

logger = logging.getLogger(__name__)

class AutonomousNeuroplasticity:
    """Uses LLM reasoning to determine memory strengthening, decay, or pruning."""

    def __init__(self, kg: KnowledgeGraph, model: str = "llama3",
                 amygdala: Optional[Amygdala] = None):
        self.kg = kg
        self.model = model
        self.amygdala = amygdala or Amygdala()

    def evaluate_and_optimize(self) -> Dict[str, Any]:
        """
        Fetches a batch of the graph connections, hands them to the LLM
        to evaluate relevance, obsolescence, and redundancy, then executes
        the LLM's recommended graph operations.
        """
        if not self.kg.driver:
            return {"status": "offline", "actions_taken": 0}

        # 1. Base Math Heuristic: Decay & Orphan Prune
        heuristic_actions = self.apply_baseline_decay()
        
        # 2. Fetch current memory state (we grab a sample or the whole active graph depending on size)
        context = self._fetch_graph_sample()
        if not context:
            return {"status": "no_data", "actions_taken": heuristic_actions}

        # 3. Ask LLM to evaluate the memory graph autonomously
        prompt = self._build_evaluation_prompt(context)
        
        try:
            response = ollama.chat(model=self.model, messages=[
                {"role": "system", "content": "You are the autonomous memory manager of a Neo4j knowledge graph."},
                {"role": "user", "content": prompt}
            ])
            
            reply = response['message']['content']
            decisions = self._parse_llm_decisions(reply)
            
            # 4. Apply the LLM's decisions back to the graph
            llm_actions = self._execute_decisions(decisions)
            
            return {
                "status": "success",
                "actions_taken": heuristic_actions + llm_actions,
                "heuristic_actions": heuristic_actions,
                "llm_actions": llm_actions,
                "decisions": decisions
            }
            
        except Exception as e:
            logger.error(f"Autonomous memory optimization error: {e}")
            return {"status": "error", "error": str(e), "actions_taken": heuristic_actions}

    def _fetch_graph_sample(self, limit: int = 50) -> List[Dict[str, Any]]:
        query = """
        MATCH (a)-[r]->(b)
        RETURN a.name AS source, type(r) AS relation, b.name AS target, r.strength AS strength
        LIMIT $limit
        """
        with self.kg.driver.session() as session:
            result = session.run(query, limit=limit)
            return [{"source": rec["source"], "relation": rec["relation"], "target": rec["target"], "strength": rec["strength"]} for rec in result]

    def apply_baseline_decay(self, decay_rate: float = 0.1, prune_threshold: float = 0.0) -> int:
        """
        Runs the baseline mathematical heuristic over the graph infrastructure.
        - Reduces non-layer structural connections by `decay_rate`
        - Prunes edges that fall below the `prune_threshold`
        - Cleans up orphan non-root nodes
        Returns the number of edges decayed + orphans pruned.
        """
        if not self.kg.driver:
            return 0
            
        actions = 0
        # Build the emotional immunity clause from the Amygdala
        immunity_clause = self.amygdala.get_decay_immunity_cypher()
        decay_query = f"""
        MATCH ()-[s]->()
        // Do not decay the core topology
        WHERE type(s) <> 'IN_LAYER' AND type(s) <> 'PEER_LAYER'
        // Amygdala: protect emotionally significant edges
        {immunity_clause}
        // Base heuristic: simply subtract the decay rate
        SET s.strength = s.strength - $decay_rate
        WITH s
        WHERE s.strength <= $prune_threshold
        DELETE s
        """
        
        orphan_query = """
        MATCH (n)
        WHERE NOT (n)--() AND NOT n:LayerRoot AND n.name <> 'NARRATIVE'
        DELETE n
        RETURN count(*) as pruned
        """
        
        with self.kg.driver.session() as session:
            try:
                # 1. Decay the edges (and prune ones below 0 threshold)
                res = session.run(decay_query, decay_rate=decay_rate, prune_threshold=prune_threshold)
                actions += res.consume().counters.properties_set
                
                # 2. Prune any orphans generated by edge death
                res_orphans = session.run(orphan_query)
                orphans = res_orphans.peek()
                if orphans:
                    actions += orphans['pruned']
            except Exception as e:
                logger.warning(f"Baseline decay failed: {e}")
                
        return actions

    def _build_evaluation_prompt(self, context: List[Dict[str, Any]]) -> str:
        graph_str = json.dumps(context, indent=2)
        return f"""Review the following slice of the memory graph:
{graph_str}

Evaluate these memories. 
1. Are there outdated, contradictory, or useless facts? You should "PRUNE" them.
2. Are there highly critical, structural facts that should be "STRENGTHENED"?
3. Are there facts that are losing relevance and should "DECAY"?

Return your decisions as a JSON array EXACTLY matching this format:
```json
[
  {{"action": "PRUNE", "source": "User", "relation": "LIKES", "target": "Old Band"}},
  {{"action": "STRENGTHEN", "source": "System", "relation": "IS", "target": "Online"}},
  {{"action": "DECAY", "source": "User", "relation": "ATE", "target": "Pizza Yesterday"}}
]
```
If the graph looks generally optimal, return an empty array `[]`. Return ONLY the JSON array.
"""

    def _parse_llm_decisions(self, text: str) -> List[Dict[str, str]]:
        try:
            if "```json" in text:
                json_block = text.split("```json")[-1].split("```")[0].strip()
            elif "```" in text:
                json_block = text.split("```")[1].split("```")[0].strip()
            else:
                json_block = text.strip()
                
            parsed = json.loads(json_block)
            if isinstance(parsed, list):
                return parsed
            return []
        except json.JSONDecodeError:
            logger.warning("Failed to parse LLM memory optimization decisions.")
            return []

    def _execute_decisions(self, decisions: List[Dict[str, str]]) -> int:
        actions = 0
        prune_query = "MATCH (a {name: $src})-[r]->(b {name: $tgt}) WHERE type(r) = $rel DELETE r"
        strengthen_query = "MATCH (a {name: $src})-[r]->(b {name: $tgt}) WHERE type(r) = $rel SET r.strength = coalesce(r.strength, 1.0) + 0.5"
        decay_query = "MATCH (a {name: $src})-[r]->(b {name: $tgt}) WHERE type(r) = $rel SET r.strength = coalesce(r.strength, 1.0) - 0.2"

        with self.kg.driver.session() as session:
            for d in decisions:
                action = d.get("action")
                src = d.get("source")
                rel = d.get("relation")
                tgt = d.get("target")
                
                if not all([action, src, rel, tgt]):
                    continue
                    
                clean_rel = "".join(c for c in rel if c.isalnum() or c == "_").upper()
                
                try:
                    if action == "PRUNE":
                        session.run(prune_query, src=src, tgt=tgt, rel=clean_rel)
                    elif action == "STRENGTHEN":
                        session.run(strengthen_query, src=src, tgt=tgt, rel=clean_rel)
                    elif action == "DECAY":
                        session.run(decay_query, src=src, tgt=tgt, rel=clean_rel)
                    actions += 1
                except Exception as e:
                    logger.warning(f"Failed to execute LLM graph action {action} on {src}->{tgt}: {e}")
                    
            # Cleanup orphaned nodes mathematically if requested/needed even autonomously, 
            # as disconnected nodes aren't sent in relationships query.
            try:
                session.run("MATCH (n) WHERE NOT (n)--() DELETE n")
            except Exception as e:
                logger.warning(f"Failed to execute cleanup: {e}")
            
        return actions
